spring:
  application:
    name: terminal-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    include: dockerEc2, jwt, session, db
#logging:
#  level:
#    root: debug
